feat: replace op-node with base-consensus

diff --git a/nethermind/Dockerfile b/nethermind/Dockerfile
--- a/nethermind/Dockerfile
+++ b/nethermind/Dockerfile
@@ -13,6 +13,22 @@ RUN . /tmp/versions.env && git clone $OP_NODE_REPO --branch $OP_NODE_TAG --singl
 RUN . /tmp/versions.env && cd op-node && \
     just VERSION=$OP_NODE_TAG op-node
 
+FROM rust:1.88 AS base-consensus
+
+WORKDIR /app
+
+COPY versions.env /tmp/versions.env
+
+RUN apt-get update && apt-get -y upgrade && \
+    apt-get install -y git libclang-dev pkg-config curl build-essential && \
+    rm -rf /var/lib/apt/lists/*
+
+RUN . /tmp/versions.env && git clone $BASE_NODE_REPO . && \
+    git checkout tags/$BASE_NODE_TAG && \
+    bash -c '[ "$(git rev-parse HEAD)" = "$BASE_NODE_COMMIT" ]' || (echo "Commit hash verification failed" && exit 1)
+
+RUN cargo build --bin base-consensus --profile maxperf
+
 FROM mcr.microsoft.com/dotnet/sdk:10.0-noble AS build
 
 ARG BUILD_CONFIG=release
@@ -25,7 +41,7 @@ COPY versions.env /tmp/versions.env
 RUN . /tmp/versions.env && git clone $NETHERMIND_REPO --branch $NETHERMIND_TAG --single-branch . && \
     git switch -c $NETHERMIND_TAG && \
     bash -c '[ "$(git rev-parse HEAD)" = "$NETHERMIND_COMMIT" ]'
-    
+
 RUN TARGETARCH=${TARGETARCH#linux/} && \
     arch=$([ "$TARGETARCH" = "amd64" ] && echo "x64" || echo "$TARGETARCH") && \
     echo "Using architecture: $arch" && \
@@ -43,8 +59,11 @@ WORKDIR /app
 
 COPY --from=build /publish ./
 COPY --from=op /app/op-node/bin/op-node ./
+COPY --from=base-consensus /app/target/maxperf/base-consensus ./
 COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
 COPY nethermind/nethermind-entrypoint ./execution-entrypoint
 COPY op-node-entrypoint .
+COPY base-consensus-entrypoint .
+COPY consensus-entrypoint .
 
 CMD ["/usr/bin/supervisord"]
