my stuff

diff --git a/reth/reth-entrypoint b/reth/reth-entrypoint
--- a/reth/reth-entrypoint
+++ b/reth/reth-entrypoint
@@ -1,6 +1,27 @@
 #!/bin/bash
 set -eu
 
+get_public_ip() {
+  # Define a list of HTTP-based providers
+  local PROVIDERS=(
+    "http://ifconfig.me"
+    "http://api.ipify.org"
+    "http://ipecho.net/plain"
+    "http://v4.ident.me"
+  )
+  # Iterate through the providers until an IP is found or the list is exhausted
+  for provider in "${PROVIDERS[@]}"; do
+    local IP
+    IP=$(curl -s "$provider")
+    # Check if IP contains a valid format (simple regex for an IPv4 address)
+    if [[ $IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+      echo "$IP"
+      return 0
+    fi
+  done
+  return 1
+}
+
 IPC_PATH="/data/reth.ipc"
 RETH_DATA_DIR=/data
 RPC_PORT="${RPC_PORT:-8545}"
@@ -35,10 +56,19 @@ fi
 mkdir -p "$RETH_DATA_DIR"
 echo "$OP_NODE_L2_ENGINE_AUTH_RAW" > "$OP_NODE_L2_ENGINE_AUTH"
 
-exec "$BINARY" node \
+# public-facing P2P node, advertise public IP address
+if PUBLIC_IP=$(get_public_ip); then
+  echo "fetched public IP is: $PUBLIC_IP"
+else
+  echo "Could not retrieve public IP."
+  exit 8
+fi
+
+export OP_NODE_P2P_ADVERTISE_IP=$PUBLIC_IP
+
+exec $BINARY node \
   -vvv \
   --datadir="$RETH_DATA_DIR" \
-  --log.stdout.format json \
   --ws \
   --ws.origins="*" \
   --ws.addr=0.0.0.0 \
@@ -53,11 +83,14 @@ exec "$BINARY" node \
   --authrpc.addr=0.0.0.0 \
   --authrpc.port="$AUTHRPC_PORT" \
   --authrpc.jwtsecret="$OP_NODE_L2_ENGINE_AUTH" \
-  --metrics=0.0.0.0:"$METRICS_PORT" \
-  --max-outbound-peers=100 \
+  --max-outbound-peers=10 \
   --chain "$RETH_CHAIN" \
   --rollup.sequencer-http="$RETH_SEQUENCER_HTTP" \
   --rollup.disable-tx-pool-gossip \
   --discovery.port="$DISCOVERY_PORT" \
   --port="$P2P_PORT" \
   $ADDITIONAL_ARGS
+
+  #--websocket-url="$RETH_FB_WEBSOCKET_URL" \
+  #--metrics=0.0.0.0:"$METRICS_PORT" \
+  #--log.stdout.format json \
